<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <?php
    $Js = $this->getJs();
    $Css = $this->getCss();
    ?>
    <?php foreach ($Js as $j): ?>
        <script src="<?php echo Mage::getBaseUrl() . 'js/' . $j ?>"></script>
    <?php endforeach; ?>
    <?php foreach ($Css as $c): ?>
        <link rel=" stylesheet" href="<?php echo Mage::getBaseUrl() . 'css/' . $c ?>">
        </link>
    <?php endforeach; ?>
    <!-- Bootstrap CSS -->
    <link href=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Font Awesome for icons -->
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

</head>