<?php
$category = $this->getCategory();
?>

<body>
    <div class="container-category-list">
        <h2>Category List</h2>
        <div class="add-btn">
            <a href="<?php echo $this->getUrl('*/*/new'); ?>">➕ Add New Category</a>
        </div>
        <?php $this->getChildHtml('csv'); ?>

        <div class="toolbar">
            <?php $this->getChildHtml('toolbar'); ?>
        </div>
        <?php if (!empty($this->getCategory())): ?>
            <table class="table table-bordered table-hover text-center">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Description</th>

                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCategory() as $category): ?>
                        <tr>
                            <td><?php echo htmlspecialchars($category->getCategoryId()); ?></td>
                            <td><?php echo htmlspecialchars($category->getname()); ?></td>
                            <td><?php echo htmlspecialchars($category->getdescription()); ?></td>

                            <td>
                                <a href='<?php echo $this->getUrl("*/*/new") ?>/?id=<?php echo $category->getCategoryId(); ?>'>
                                    <i class='fa fa-edit' style="color:blue;"></i></a>
                            </td>
                            <td>
                                <a
                                    href='<?php echo $this->getUrl("*/*/delete") ?>/?id=<?php echo $category->getProduct_id(); ?>'>
                                    <i class='fa fa-trash' style="color:red;"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p class="text-center">No Categories Found</p>
        <?php endif; ?>
    </div>
</body>

</html>