<?php

$result = $this->getProduct();

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Detail Form</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background: linear-gradient(135deg, #eaebe1, rgb(140, 141, 125));
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            min-height: 100vh;
            overflow-y: auto;
        }

        h2 {
            text-align: center;
            color: #444444;
            margin-bottom: 20px;
        }

        button {
            border: none;
            outline: none;
            background: none;
            padding: 0;
            font-size: 16px;
            color: blue;
        }

        table {
            width: 90%;
            margin-top: 30px;
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
        }

        th,
        td {
            padding: 10px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }

        td {
            background-color: #f9f9f9;
        }

        .col-md-2 {
            display: flex;
            justify-content: flex-end;
            width: 90%;
        }

        .add-new {
            color: #fff;
            background-color: #1E90FF;
            font-size: 15px;
            font-weight: 600;
            text-align: center;
            text-transform: uppercase;
            padding: 7px 10px;
            /* margin: 0 0 20px; */
            display: block;
            transition: all 0.3s;
        }
    </style>
</head>

<body>
    <h2>All Product</h2>
    <div class="col-md-2">
        <a class="add-new" href="./new">add product</a>
    </div>
    <?php if (count($this->getProduct()) > 0): ?>
        <table>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Category_Id</th>
                <th>Description</th>
                <th>Price</th>
                <th>Warranty</th>
                <th>Color</th>
                <!-- <th>Weight</th> -->
                <!-- <th>Size</th> -->
                <!-- <th>Material</th> -->
                <!-- <th>Brand</th> -->
                <!-- <th>Dimensions</th> -->
                <!-- <th>Releasedate</th> -->
                <!-- <th>Status</th> -->
                <th>Edit</th>
                <th>Delete</th>
            </tr>

            <?php foreach ($this->getProduct() as $result): ?>
                <tr>
                    <td>
                        <?php echo $result->getProduct_id(); ?>
                    </td>
                    <td>
                        <?php echo $result->getName(); ?>
                    </td>
                    <td>
                        <?php echo $result->getCategory_id(); ?>
                    </td>
                    <td>
                        <?php echo $result->getDescription(); ?>
                    </td>
                    <td>
                        <?php echo $result->getPrice(); ?>
                    </td>
                    <td>
                        <?php echo $result->getWarranty(); ?>
                    </td>
                    <td>
                        <?php echo $result->getColor(); ?>
                    </td>
                    <!-- <td>
                        <?php //echo $result->getWeight(); ?>
                    </td> -->
                    <!-- <td>
                        <?php //echo $result->getSize(); ?>
                    </td>
                    <td>
                        <?php //echo $result->getMaterial(); ?>
                    </td>
                    <td>
                        <?php //echo $result->getBrand(); ?>
                    </td>
                    <td>
                        <?php //echo $result->getDimensions(); ?>
                    </td>
                    <td>
                        <?php //echo $result->getReleasedate(); ?>
                    </td>

                    <td>

                        <?php //echo $result->getStatusText(); ?>
                    </td> -->
                    <td>
                        <a href='<?php echo $this->getUrl("*/*/new") ?>/?id=<?php echo $result->getProduct_id(); ?>'> <i
                                class='fa fa-edit' style="color:blue;"></i></a>
                    </td>
                    <td>
                        <a href='<?php echo $this->getUrl("*/*/delete") ?>/?id=<?php echo $result->getProduct_id(); ?>'> <i
                                class='fa fa-trash' style="color:red;"></i></a>
                        <!-- <form method="POST" action="?m=admin&v=product&a=deleteProduct">
                    <button name="deleteid" value="<?php echo $result->getProduct_id(); ?>"
                        onclick="return confirm('Are you sure you want to delete this record?')">
                        <i class="fas fa-trash" style="color:red;"></i>
                    </button>
                </form> -->
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <p>No Product available. </p>
    <?php endif; ?>
</body>

</html>