<?php

$category = $this->getCategory();
?>

<div class="container">
    <h2>Category List</h2>
    <?php if (!empty($this->getCategory())): ?>
        <table class="table table-bordered table-hover text-center">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th>Product Count</th>
                    <th>Visibility</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->getCategory() as $category): ?>
                    <tr>
                        <td><?php echo htmlspecialchars($category->getCategoryId()); ?></td>
                        <td><?php echo htmlspecialchars($category->getname()); ?></td>
                        <td><?php echo htmlspecialchars($category->getdescription()); ?></td>
                        <td><img src="/Ecommerce/<?php echo htmlspecialchars($category->getImage()); ?>" width="50" height="50">
                        </td>
                        <td><?php echo htmlspecialchars($category->getProductCount()); ?></td>
                        <td><?php echo htmlspecialchars(str_replace(',', ', ', $category->getVisibility())); ?></td>
                        <td><?php echo htmlspecialchars($category->getCreatedAt()); ?></td>
                        <td><?php echo htmlspecialchars($category->getUpdatedAt()); ?></td>
                        <td>
                            <form action='?m=Admin&v=Category&a=deleteCategory' method='POST' style='display:inline-block;'>
                                <input type='hidden' name='id'
                                    value='<?php echo htmlspecialchars($category->getcategoryId()); ?>'>
                                <button type='submit' class='btn btn-danger btn-sm'
                                    onclick='return confirm("Are you sure you want to delete this category?")'>🗑
                                    Delete</button>
                            </form>

                            <a href="?m=Admin&v=Category&a=view&id=<?php echo htmlspecialchars($category->getCategoryId()); ?>"
                                class="btn-edit">Edit</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p class="text-center">No Categories Found</p>
    <?php endif; ?>
</div>